services:
  neo4j:
    image: neo4j:3.5.14-enterprise
    container_name: airbyte-neo4j-entity-tests
    ports:
      # we do not use the default bolt port 7687 to be able to run tests when we have started the neo4 container used for development 
      - 7688:7687
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
